#Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "Tize" do

pod 'Parse'
pod 'ParseUI'
pod 'SVProgressHUD'
pod 'UICKeyChainStore'

end

